### ISSUE TITLE
Implement Server-side Playlist Functions

### ISSUE THREAD

**Issue by DJTai** [mcastorena/CECS327#13]
Currently, the playlist controls only function on the client-side. This functionality needs to be implemented server-side.
**TODO:**
- [x] Delete playlists
- [x] Add song to playlist from search (drag-n-drop on client -> edit on client -> finalize on server)

For now, that is all.

**Comment by Matcunningham** [comment]
Complete, but buggy. Might need to be updated depending on how call semantics are implemented.

**Comment by Matcunningham** [comment]
Fixed bugs. These issues are working now.
